apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
  labels:
    env: test
spec:
  replicas: 5
  selector:
    app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          env:
            - name: sanjay
              value: testing  
